spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#      h2 DB를 임시로 생성하여 사용할 수 있다.

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  #        page 파라미터를 0 -> 1부터 시작하도록 한다.

  jpa:
    defer-datasource-initialization: true

#  sql:
#    init-mode: always
#    always는 항상 넣고, never를 작성하면 넣지 않는다.
#    data.sql를 통해 웹 애플리케이션을 실행하면 데이터가 자동으로 들어가게 하는 코드

  datasource:
    url: jdbc:h2:mem:islog
    username: sa
    password:
    driver-class-name: org.h2.Driver

bis:
#  hello: "world"
#  hello:
#    - "a"
#    - "b"
#    - "c"
#  hello:
#    name: "bis"
#    home: "seoul"
#    age: 35
  jwtKey: "thisIsSecretKeythisIsSecretKeythisIsSecretKeythisIsSecretKeythisIsSecretKey"