### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json
#헤더와 본문을 구분하기 위해 한 줄 띄어야 한다.

{
  "email": "saymay10@naver.com",
  "password": "1234"
}

### 인증 페이지 요청
GET http://localhost:8080/test2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk2NzY5ODI5fQ.V1Q810fPUGsi8Q3BWGmn5xlRIWjOtC-iahKU8ugAiN8
#Cookie: SESSION=f3b91d7b-8f46-4ff1-b379-536ea090bd4c